import tkinter as tk
root=tk.Tk()
root.geometry("1000x1000")
left_frame = tk.Frame(root, bg="#C397C3", width=40, height=1000)
left_frame.pack(side="left", fill="both", expand=False)
left_label = tk.Label(left_frame, text="Section 1", fg="black", bg="#C397C3")
right_frame = tk.Frame(root, bg="#C397C3", width=40, height=1000)
right_frame.pack(side="right", fill="both", expand=False)
right_label = tk.Label(right_frame, text="Section 1", fg="black", bg="black")
butoon1 = tk.Button(left_frame, text="Button 1", fg="black", bg="blue", width=20, height=2)
butoon1.pack(pady=10)
root.mainloop()